/**
 * Central Bengali UX copy dictionary — one terminology source for the whole product.
 * All user-facing strings should come from here (or page-level constants reusing these terms).
 */

export const T = {
  appName: 'MERQO Retail Suite',
  brand: 'MERQO.',
  currency: '৳',
  save: 'সংরক্ষণ করুন',
  saving: 'সংরক্ষণ হচ্ছে…',
  cancel: 'বাতিল করুন',
  close: 'বন্ধ করুন',
  confirm: 'নিশ্চিত করুন',
  proceed: 'চালিয়ে যান',
  back: 'পেছনে',
  next: 'পরবর্তী',
  search: 'খুঁজুন',
  add: 'যোগ করুন',
  edit: 'সম্পাদনা',
  remove: 'মুছে ফেলুন',
  print: 'প্রিন্ট',
  preview: 'প্রিভিউ',
  download: 'ডাউনলোড',
  export: 'এক্সপোর্ট',
  import: 'ইমপোর্ট',
  refresh: 'রিফ্রেশ',
  filter: 'ফিল্টার',
  total: 'মোট',
  subtotal: 'উপমোট',
  discount: 'ছাড়',
  tax: 'ভ্যাট/ট্যাক্স',
  paid: 'পরিশোধিত',
  due: 'বকেয়া',
  change: 'ফেরত',
  balance: 'ব্যালেন্স',
  date: 'তারিখ',
  from: 'শুরু',
  to: 'শেষ',
  amount: 'পরিমাণ',
  quantity: 'পরিমাণ',
  price: 'দাম',
  actions: 'কার্যক্রম',
  status: 'অবস্থা',
  notes: 'মন্তব্য',
  description: 'বিবরণ',
  reference: 'রেফারেন্স',
  phone: 'মোবাইল',
  address: 'ঠিকানা',
  name: 'নাম',
  empty: '—',
  today: 'আজ',
  all: 'সবগুলো',
  yes: 'হ্যাঁ',
  no: 'না',
  loading: 'লোড হচ্ছে…',
  noData: 'কোনো তথ্য পাওয়া যায়নি।',
  selectDate: 'তারিখ নির্বাচন করুন',
  saved: 'তথ্য সংরক্ষণ করা হয়েছে।',
  deleted: 'মুছে ফেলা হয়েছে।',
  failed: 'দুঃখিত, কাজটি সম্পন্ন করা যায়নি। আবার চেষ্টা করুন।',
  required: 'এই ঘরটি পূরণ করা আবশ্যক।',
  invalidAmount: 'সঠিক টাকার পরিমাণ দিন।',
  noPermission: 'এই কাজটি করার অনুমতি আপনার নেই।',
  confirmDeleteTitle: 'মুছে ফেলার নিশ্চয়তা',
  networkNeverNeeded: 'ইন্টারনেট ছাড়াই চলবে',
} as const;

export const NAV_BN = [
  { id: 'dashboard', label: 'ড্যাশবোর্ড' },
  { id: 'sales', label: 'বিক্রয়' },
  { id: 'purchases', label: 'ক্রয়' },
  { id: 'products', label: 'পণ্য ও স্টক' },
  { id: 'customers', label: 'কাস্টমার' },
  { id: 'suppliers', label: 'সরবরাহকারী' },
  { id: 'accounts', label: 'হিসাব' },
  { id: 'agent', label: 'এজেন্ট ব্যাংকিং' },
  { id: 'reports', label: 'রিপোর্ট' },
  { id: 'notifications', label: 'নোটিফিকেশন' },
  { id: 'employees', label: 'কর্মচারী' },
  { id: 'settings', label: 'সেটিংস' },
] as const;

/** Map technical error codes to natural Bengali messages. */
export function bnError(codeOrMessage: string): string {
  const map: Record<string, string> = {
    INVALID_AMOUNT: 'টাকার পরিমাণ সঠিক নয়। অনুগ্রহ করে সঠিক পরিমাণ দিন।',
    BARCODE_DUPLICATE: 'এই বারকোডটি ইতিমধ্যে অন্য একটি পণ্যের সাথে যুক্ত আছে।',
    SKU_DUPLICATE: 'এই SKU-টি ইতিমধ্যে ব্যবহার করা হয়েছে। অন্য একটি SKU দিন।',
    PHONE_DUPLICATE: 'এই মোবাইল নম্বরটি ইতিমধ্যে ব্যবহার করা হয়েছে।',
    INVALID_PHONE: 'মোবাইল নম্বরটি সঠিক নয়। উদাহরণ: 017XXXXXXXX অথবা +88017XXXXXXXX।',
    INVALID_EMAIL: 'ইমেইল ঠিকানাটি সঠিক নয়। যাচাই করে আবার চেষ্টা করুন।',
    USERNAME_DUPLICATE: 'এই ইউজারনামটি ইতিমধ্যে ব্যবহার করা হয়েছে।',
    INSUFFICIENT_STOCK: 'স্টকে পর্যাপ্ত পণ্য নেই।',
    NEGATIVE_STOCK_BLOCKED: 'স্টক শূন্যের নিচে নেওয়া যাবে না। সেটিংস থেকে নীতি পরিবর্তন করুন অথবা স্টক যোগ করুন।',
    OVERPAYMENT_BLOCKED: 'পেমেন্টের পরিমাণ মোট বিলের চেয়ে বেশি। অতিরিক্ত টাকা অগ্রিম হিসেবে রাখতে চাইলে অগ্রিম নীতি চালু করুন।',
    INVALID_TOTAL: 'বিলের মোট হিসাব সঠিক নয়। আবার চেষ্টা করুন।',
    EMPTY_CART: 'কার্টে কোনো পণ্য নেই। প্রথমে পণ্য যোগ করুন।',
    CUSTOMER_NOT_FOUND: 'কাস্টমার খুঁজে পাওয়া যায়নি।',
    SUPPLIER_NOT_FOUND: 'সরবরাহকারী খুঁজে পাওয়া যায়নি।',
    PRODUCT_NOT_FOUND: 'পণ্য খুঁজে পাওয়া যায়নি।',
    PRODUCT_INACTIVE: 'পণ্যটি নিষ্ক্রিয় অবস্থায় আছে।',
    SALE_NOT_FOUND: 'বিক্রয় রেকর্ড খুঁজে পাওয়া যায়নি।',
    SALE_ALREADY_VOID: 'এই ইনভয়েসটি ইতিমধ্যে বাতিল করা হয়েছে।',
    PURCHASE_NOT_FOUND: 'ক্রয় রেকর্ড খুঁজে পাওয়া যায়নি।',
    ACCOUNT_NOT_FOUND: 'হিসাব খুঁজে পাওয়া যায়নি।',
    INSUFFICIENT_BALANCE: 'নির্বাচিত হিসাবে পর্যাপ্ত ব্যালেন্স নেই।',
    SAME_ACCOUNT: 'একই হিসাবে স্থানান্তর করা যাবে না। ভিন্ন হিসাব নির্বাচন করুন।',
    INVALID_CREDENTIALS: 'ইউজারনাম অথবা পাসওয়ার্ড সঠিক নয়।',
    AUTH_LOCKED: 'অনেকবার ভুল চেষ্টা হয়েছে। ১০ মিনিট পর আবার চেষ্টা করুন।',
    PATH_NOT_ALLOWED: 'এই ফাইলটি খোলার অনুমতি নেই।',
    USER_INACTIVE: 'এই ব্যবহারকারীর অ্যাকাউন্ট নিষ্ক্রিয় করা হয়েছে।',
    USER_NOT_FOUND: 'ব্যবহারকারী খুঁজে পাওয়া যায়নি।',
    NO_PERMISSION: 'এই কাজটি করার অনুমতি আপনার নেই।',
    NOT_AUTHENTICATED: 'অনুগ্রহ করে আবার লগইন করুন।',
    INVALID_QTY: 'পণ্যের পরিমাণ সঠিক নয়।',
    INVALID_PRICE: 'পণ্যের দাম সঠিক নয়।',
    RETURN_EXCEEDS_SALE: 'ফেরতের পরিমাণ বিক্রীত পরিমাণের চেয়ে বেশি হতে পারবে না।',
    RETURN_EXCEEDS_PURCHASE: 'ফেরতের পরিমাণ ক্রীত পরিমাণের চেয়ে বেশি হতে পারবে না।',
    BACKUP_NOT_FOUND: 'ব্যাকআপ ফাইল খুঁজে পাওয়া যায়নি।',
    BACKUP_INVALID: 'ব্যাকআপ ফাইলটি বৈধ নয় অথবা ক্ষতিগ্রস্ত।',
    IMPORT_EMPTY: 'ফাইলে কোনো বৈধ তথ্য পাওয়া যায়নি।',
    IMPORT_ROW_ERROR: 'ফাইলের কিছু সারিতে ভুল আছে। অনুগ্রহ করে সংশোধন করে আবার চেষ্টা করুন।',
    PRINTER_UNAVAILABLE: 'প্রিন্টার পাওয়া যাচ্ছে না। প্রিন্টার সংযোগ পরীক্ষা করুন অথবা PDF সংরক্ষণ করুন।',
    PRINT_FAILED: 'প্রিন্ট করা যায়নি। আবার চেষ্টা করুন অথবা PDF সংরক্ষণ করুন।',
    WEAK_PASSWORD: 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।',
    CANNOT_DELETE_SELF: 'নিজের অ্যাকাউন্ট মুছে ফেলা যাবে না।',
    CANNOT_DELETE_LAST_ADMIN: 'সর্বশেষ অ্যাডমিন অ্যাকাউন্ট মুছে ফেলা যাবে না।',
    HAS_TRANSACTIONS: 'এই রেকর্ডের সাথে লেনদেন জড়িত থাকায় মুছে ফেলা যাবে না। প্রয়োজনে নিষ্ক্রিয় করুন।',
    INVALID_DATE_RANGE: 'তারিখের সীমা সঠিক নয়।',
    EXPIRED_PRODUCT_SALE: 'মেয়াদোত্তীর্ণ পণ্য বিক্রয় করা যাবে না।',
    SETUP_ALREADY_DONE: 'সেটআপ ইতিমধ্যে সম্পন্ন হয়েছে।',
    CUSTOMER_REQUIRED_FOR_DUE: 'বকেয়া বিক্রয়ের জন্য কাস্টমার নির্বাচন করা আবশ্যক।',
    SUPPLIER_REQUIRED_FOR_DUE: 'বকেয়া ক্রয়ের জন্য সরবরাহকারী নির্বাচন করা আবশ্যক।',
    INVALID_DISCOUNT: 'ছাড়ের পরিমাণ সঠিক নয়।',
    PAYMENT_MISMATCH: 'পেমেন্টের হিসাব মিলছে না। আবার চেষ্টা করুন।',
    REQUIRED: 'প্রয়োজনীয় তথ্য দিন।',
    UNKNOWN_ACTION: 'অজানা নির্দেশ।',
    DB_ERROR: 'তথ্য সংরক্ষণে সমস্যা হয়েছে। আবার চেষ্টা করুন।',
  };
  if (map[codeOrMessage]) return map[codeOrMessage];
  // Never leak raw SQL/technical text:
  if (/constraint|SQLITE|SyntaxError|undefined|null|Error:/i.test(codeOrMessage)) return T.failed;
  return codeOrMessage.length > 160 ? T.failed : codeOrMessage;
}
